---
- name: join k8s cluster
  shell: "kubeadm join --token {{ hostvars[master].mastertoken }} {{ master }}:6443"

- name: enable kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

