---
- name: start contrail webui
  docker_service:
    project_name: contrail-webui
    pull: yes
    definition:
      version: '2'
      services:
        network:
          image: docker.io/kubernetes/pause
          network_mode: "host"
          volumes:
           - /etc/hosts:/etc/hosts
        web:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-webui-web:{{ CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          volumes:
            - /var/log/contrail
          depends_on:
            - network
          restart: on-failure
        job:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-webui-job:{{ CONTRAIL_VERSION }}"
          network_mode: "service:network"
          env_file: /tmp/common.env
          volumes:
            - /var/log/contrail
          depends_on:
            - network
          restart: on-failure
