---
- name: start contrail config database
  docker_service:
    project_name: contrail-config-database
    pull: yes
    definition:
      version: '2'
      services:
        network:
          image: docker.io/kubernetes/pause
          network_mode: "host"
          volumes:
           - /etc/hosts:/etc/hosts
        nodemgr:
          image: "{{ CONTAINER_REGISTRY }}/contrail-nodemgr:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          environment:
            - NODE_TYPE=contrail-database
          network_mode: "service:network"
          volumes:
            - /var/log/contrail:/var/log/contrail
          depends_on:
            - network
          restart: on-failure
        cassandra:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-database-cassandra:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          environment:
           - CASSANDRA_START_RPC=true
           - CASSANDRA_CLUSTER_NAME=contrail_database
          volumes:
           - /var/lib/cassandra/data
          network_mode: "service:network"
          depends_on:
            - network
          restart: on-failure
        zookeeper:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-database-zookeeper:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          volumes:
           - /data
          network_mode: "service:network"
          depends_on:
            - network
          restart: on-failure
        rabbitmq:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-database-rabbitmq:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          environment:
           - RABBITMQ_ERLANG_COOKIE=abcdefg
          network_mode: "service:network"
          depends_on:
            - network
          restart: on-failure
        redis:
          image: "{{ CONTAINER_REGISTRY }}/contrail-controller-database-redis:{{ contrail_configuration.CONTRAIL_VERSION }}"
          env_file: /tmp/common.env
          network_mode: "service:network"
          depends_on:
            - network
          restart: on-failure
