---
- name: get /tmp/common.env stat
  stat:
    path: /tmp/common.env
  register: st

- name: delete /tmp/common.env if exists
  file:
    path: /tmp/common.env
    state: absent
  when: st.stat.exists is defined and st.stat.exists and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create /tmp/common.env
  file:
    path: /tmp/common.env
    state: touch
  when: CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: populate common.env
  lineinfile: dest=/tmp/common.env regexp='.*{{ item.key }}$' line="{{ item.key }}={{ item.value }}" state=present
  with_dict: "{{ contrail_configuration }}"
  when: CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail config datqbase
  include: create_config_database.yml
  when: hostvars[inventory_hostname].roles.configdb is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail config
  include: create_config.yml
  when: hostvars[inventory_hostname].roles.config is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail webui
  include: create_webui.yml
  when: hostvars[inventory_hostname].roles.webui is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail control
  include: create_control.yml
  when: hostvars[inventory_hostname].roles.control is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail analytics database
  include: create_analytics_db.yml
  when: hostvars[inventory_hostname].roles.analyticsdb is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail analytics
  include: create_analytics.yml
  when: hostvars[inventory_hostname].roles.analytics is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail kube manager
  include: create_kube_manager.yml
  when: hostvars[inventory_hostname].roles.k8s_master is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create cni
  include: create_k8s_cni.yml
  when: hostvars[inventory_hostname].roles.k8s_minion is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

- name: create contrail vrouter
  include: create_vrouter.yml
  when: hostvars[inventory_hostname].roles.vrouter is defined and CREATE_CONTAINERS is defined and CREATE_CONTAINERS==true

